name: Build

on:
  push:
    branches: [ main ]
    tags: ['*']
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "~1.24"

      - name: Install libudev
        run: sudo apt-get update && sudo apt-get install -y libudev-dev

      - name: Download packages
        run: go mod download

      - name: Build
        run: go build ./...
